name       : rawtherapee
version    : '5.8'
release    : 15
source     :
    - https://rawtherapee.com/shared/source/rawtherapee-5.8.tar.xz : 360528a0aae922eb5af8742f415475fb91b6d62a739da5f2804828f04ec40853
homepage   : https://rawtherapee.com/
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : A powerful cross-platform raw photo processing program
description: |
    RawTherapee is an advanced cross-platform program for developing raw photos and for processing non-raw photos. It is non-destructive, makes use of OpenMP, supports all the cameras supported by dcraw and more, and carries out its calculations in a high precision 32-bit floating point engine.
optimize   :
    - speed
    - lto
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(fftw3)
    - pkgconfig(gtk-engines-2)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(lensfun)
    - pkgconfig(libcanberra)
    - pkgconfig(libiptcdata)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(sigc++-2.0)
    - bzip2-devel
    - mercurial
setup      : |
    cat > rtgui/version.h << EOF
    #ifndef _VERSION_
    #define _VERSION_
    #define VERSION "$version"
    #endif
    EOF

    %patch -p1 < $pkgfiles/0001-fix-canon-mraw-and-sraw-regression.patch

    %cmake_ninja -DBUILD_SHARED=ON -DCACHE_NAME_SUFFIX=""
build      : |
    %ninja_build
install    : |
    %ninja_install
