name       : rawtherapee
version    : '5.7'
release    : 12
source     :
    - https://rawtherapee.com/shared/source/rawtherapee-5.7.tar.xz : dbd7c7cf7488fb97c520821eee2c745291637644b391e3ec0ed3a29701f1a9c7
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : A powerful cross-platform raw photo processing program
description: |
    A powerful cross-platform raw photo processing program
optimize   : speed
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(exiv2)
    - pkgconfig(fftw3)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-engines-2)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(lensfun)
    - pkgconfig(libcanberra)
    - pkgconfig(libiptcdata)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(sigc++-2.0)
    - bzip2-devel
    - mercurial
setup      : |
    cat > rtgui/version.h << EOF
    #ifndef _VERSION_
    #define _VERSION_
    #define VERSION "$version"
    #endif
    EOF

    %cmake -DBUILD_SHARED=ON -DCACHE_NAME_SUFFIX=""
build      : |
    %make
install    : |
    %make_install
