name       : rawtherapee
version    : '5.9'
release    : 20
source     :
    - https://rawtherapee.com/shared/source/rawtherapee-5.9.tar.xz : 8eaf28c428185c165ef5a28f69595dc77a1c98826065a1f51a28c86c7b0d4823
homepage   : https://rawtherapee.com/
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : A powerful cross-platform raw photo processing program
description: |
    RawTherapee is an advanced cross-platform program for developing raw photos and for processing non-raw photos. It is non-destructive, makes use of OpenMP, supports all the cameras supported by dcraw and more, and carries out its calculations in a high precision 32-bit floating point engine.
optimize   :
    - speed
    - lto
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(fftw3)
    - pkgconfig(gtk-engines-2)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(lensfun)
    - pkgconfig(libcanberra)
    - pkgconfig(libiptcdata)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(sigc++-2.0)
    - bzip2-devel
    - mercurial
setup      : |
    cat > rtgui/version.h << EOF
    #ifndef _VERSION_
    #define _VERSION_
    #define VERSION "$version"
    #endif
    EOF

    %cmake_ninja -DBUILD_SHARED=ON -DCACHE_NAME_SUFFIX=""
build      : |
    %ninja_build
install    : |
    %ninja_install

    rm -rf $installdir/usr/share/doc
