name       : rawtherapee
version    : 5.5
release    : 11
source     :
    - https://rawtherapee.com/shared/source/rawtherapee-5.5.tar.xz : c169c9fb37dd5183de795200338af1e597f8189b1f75a48f8688db6eb35048f0
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : A powerful cross-platform raw photo processing program
description: |
    A powerful cross-platform raw photo processing program
optimize   : speed
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(exiv2)
    - pkgconfig(fftw3)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-engines-2)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(lensfun)
    - pkgconfig(libcanberra)
    - pkgconfig(libiptcdata)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(sigc++-2.0)
    - bzip2-devel
    - mercurial
setup      : |
    cat > rtgui/version.h << EOF
    #ifndef _VERSION_
    #define _VERSION_
    #define VERSION "$version"
    #endif
    EOF

    %cmake -DBUILD_SHARED=ON -DCACHE_NAME_SUFFIX=""
build      : |
    %make
install    : |
    %make_install
