name       : rawtherapee
version    : '5.4'
release    : 9
source     :
    - http://rawtherapee.com/shared/source/rawtherapee-5.4.tar.xz : ed08c1c3caf5dd34b41ea3261d215c729eabe9734c78181e6690088471874988
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : A powerful cross-platform raw photo processing program
description: |
    A powerful cross-platform raw photo processing program
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(exiv2)
    - pkgconfig(fftw3)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-engines-2)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(lensfun)
    - pkgconfig(libcanberra)
    - pkgconfig(libiptcdata)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(sigc++-2.0)
    - bzip2-devel
    - mercurial
setup      : |
    cat > rtgui/version.h << EOF
    #ifndef _VERSION_
    #define _VERSION_
    #define VERSION "5.4"
    #endif
    EOF

    %cmake -DBUILD_SHARED=ON
build      : |
    %make
install    : |
    %make_install
