name       : rawtherapee
version    : 4.2
release    : 1
source     :
    - https://github.com/Beep6581/RawTherapee/archive/4.2.tar.gz : 1a50516ff8cfd36de58393a808b07243b3dbfa38738af1fd01e284ea87fc99bf
license    : GPL-3.0 
component  : multimedia.graphics
summary    : A powerful cross-platform raw photo processing program
description: |
    A powerful cross-platform raw photo processing program
builddeps  :
    - bzip2-devel
    - pkgconfig(exiv2)
    - pkgconfig(expat)
    - pkgconfig(fftw3)
    - pkgconfig(glib-2.0)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(gtk+-2.0)
    - libgtkmm-2-devel
    - libcairo-devel
    - pkgconfig(atkmm-1.6)
    - pkgconfig(gtk-engines-2)
    - libjpeg-turbo-devel
    - pkgconfig(lcms2)
    - pkgconfig(libcanberra)
    - pkgconfig(libiptcdata)
    - pkgconfig(sigc++-2.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(zlib)
    - mercurial
setup      : |
     cat > rtgui/version.h << EOF
     #ifndef _VERSION_
     #define _VERSION_
     #define VERSION "4.12"
     #endif
     EOF
     
     %patch -p1 < $pkgfiles/dcraw.patch
     %patch -p1 < $pkgfiles/sigc.patch     
     %cmake . \
         -DCMAKE_CXX_FLAGS="-std=c++11" \
         -DCMAKE_C_FLAGS="-std=c++11" \
build      : |
    %make
install    : |
    %make_install
