name       : rawtherapee
version    : '5.1'
release    : 6
source     :
    - http://rawtherapee.com/shared/source/rawtherapee-5.1.tar.xz : fb742065a6b2e1b89df67c70395e52ee1ebd537c86dfc473b41e7af171655b67
license    : GPL-3.0
component  : multimedia.graphics
summary    : A powerful cross-platform raw photo processing program
description: |
    A powerful cross-platform raw photo processing program
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(exiv2)
    - pkgconfig(fftw3)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-engines-2)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libcanberra)
    - pkgconfig(libiptcdata)
    - pkgconfig(libtiff-4)
    - pkgconfig(sigc++-2.0)
    - libjpeg-turbo-devel
    - mercurial
setup      : |
    cat > rtgui/version.h << EOF
    #ifndef _VERSION_
    #define _VERSION_
    #define VERSION "5.1"
    #endif
    EOF

    %cmake -DBUILD_SHARED=ON
build      : |
    %make
install    : |
    %make_install
