name       : rawtherapee
version    : 4.2
release    : 4
source     :
    - https://github.com/Beep6581/RawTherapee/archive/4.2.tar.gz : 1a50516ff8cfd36de58393a808b07243b3dbfa38738af1fd01e284ea87fc99bf
license    : GPL-3.0
component  : multimedia.graphics
summary    : A powerful cross-platform raw photo processing program
description: |
    A powerful cross-platform raw photo processing program
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(exiv2)
    - pkgconfig(fftw3)
    - pkgconfig(gtk-engines-2)
    - pkgconfig(gtkmm-2.4)
    - pkgconfig(lcms2)
    - pkgconfig(libcanberra)
    - pkgconfig(libiptcdata)
    - pkgconfig(libtiff-4)
    - pkgconfig(sigc++-2.0)
    - libjpeg-turbo-devel
    - mercurial
setup      : "cat > rtgui/version.h << EOF\n#ifndef _VERSION_\n#define _VERSION_\n\
    #define VERSION \"4.12\"\n#endif\nEOF\n \n%patch -p1 < $pkgfiles/security/CVE-2015-3885.patch\n\
    %patch -p1 < $pkgfiles/0001-Fix-sigc-slot.patch\n%patch -p1 < $pkgfiles/0001-rtgui-Use-the-system-theme-by-default.patch\n\
    %cmake -DCMAKE_C_FLAGS=\"-std=c++11\" -DCMAKE_CXX_FLAGS=\"-std=c++11\" .\n"
build      : |
    %make
install    : |
    %make_install
